// engineer-assessment-frontend/src/components/FilePreview.tsx
import { FileText } from "lucide-react";
import { useEffect, useState } from "react";
import { formatFileSize } from "../utils/formatters";

interface FilePreviewProps {
  file: File;
  onCancel: () => void;
  onSubmit: () => void;
}

export function FilePreview({ file, onCancel, onSubmit }: FilePreviewProps) {
  const [fileUrl, setFileUrl] = useState<string>("");

  useEffect(() => {
    const url = URL.createObjectURL(file);
    setFileUrl(url);
    return () => URL.revokeObjectURL(url);
  }, [file]);

  return (
    <div className="flex flex-col items-center justify-center flex-1 p-8">
      <div className="bg-white rounded-2xl shadow-lg p-8 max-w-lg w-full">
        <h2 className="text-2xl font-bold text-slate-800 mb-6 text-center">Selected File</h2>

        <div className="mb-6">
          <img src={fileUrl} alt="Receipt preview" className="w-full max-h-64 object-contain rounded-lg border border-slate-200" />
        </div>

        <div className="bg-slate-50 rounded-lg p-4 mb-6">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
              <FileText className="w-5 h-5 text-blue-600" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-slate-800 font-medium truncate">{file.name}</p>
              <p className="text-slate-500 text-sm">{formatFileSize(file.size)}</p>
            </div>
          </div>
        </div>

        <div className="flex gap-3">
          <button
            onClick={onCancel}
            className="flex-1 px-6 py-3 border border-slate-300 rounded-xl text-slate-700 
                       font-medium hover:bg-slate-50 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={onSubmit}
            className="flex-1 px-6 py-3 bg-blue-500 text-white rounded-xl font-medium 
                       hover:bg-blue-600 transition-colors"
          >
            Extract Receipt
          </button>
        </div>
      </div>
    </div>
  );
}

// frontend-vue/src/components/FilePreview.vue
<script setup lang="ts">
import { useReceiptStore } from '@/stores/receipt';
import { Sparkles, X } from 'lucide-vue-next';
import { computed, onUnmounted } from 'vue';

const store = useReceiptStore();

const imageUrl = computed(() => {
  return store.selectedFile ? URL.createObjectURL(store.selectedFile) : '';
});

onUnmounted(() => {
  if (imageUrl.value) {
    URL.revokeObjectURL(imageUrl.value);
  }
});
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 p-4">
    <div class="bg-white rounded-3xl p-6 max-w-md w-full shadow-lg border border-gray-200">
      <div class="relative mb-6">
        <img 
          :src="imageUrl" 
          alt="Receipt preview" 
          class="rounded-2xl w-full max-h-96 object-contain bg-gray-100" 
        />
        <button
          class="absolute top-3 right-3 p-2 rounded-full bg-white/80 text-slate-600 
                 hover:text-white hover:bg-red-500 transition-all"
          @click="store.cancelPreview"
        >
          <X class="w-5 h-5" />
        </button>
      </div>
      
      <p class="text-gray-600 text-center text-sm mb-6">
        {{ store.selectedFile?.name }}
      </p>
      
      <div class="flex gap-4">
        <button 
          class="flex-1 px-4 py-3 rounded-xl border border-gray-300 text-gray-700 
                 hover:bg-gray-50 hover:border-gray-400 transition-all font-medium"
          @click="store.cancelPreview"
        >
          Cancel
        </button>
        <button 
          class="flex-1 px-4 py-3 rounded-xl bg-blue-600 
                 text-white hover:bg-blue-700 transition-all 
                 font-medium flex items-center justify-center gap-2 shadow-lg shadow-blue-500/25"
          @click="store.extractData"
        >
          <Sparkles class="w-5 h-5" />
          Extract Data
        </button>
      </div>
    </div>
  </div>
</template>
