// engineer-assessment-frontend/src/components/LoadingState.tsx
import { Loader2 } from "lucide-react";

export function LoadingState() {
  return (
    <div className="flex flex-col items-center justify-center flex-1 p-8">
      <div className="bg-white rounded-2xl shadow-lg p-12 max-w-md w-full text-center">
        <div className="mb-6">
          <Loader2 className="w-16 h-16 text-blue-500 animate-spin mx-auto" />
        </div>

        <h2 className="text-2xl font-bold text-slate-800 mb-2">Hang Tight!</h2>
        <p className="text-slate-600">We're reading your receipt. This usually takes a few seconds...</p>
      </div>
    </div>
  );
}

// frontend-vue/src/components/LoadingState.vue
<script setup lang="ts">
import { Loader2 } from 'lucide-vue-next';
</script>

<template>
  <div class="page-container">
    <div class="text-center">
      <div class="mb-6">
        <Loader2 class="w-16 h-16 text-blue-600 animate-spin mx-auto" />
      </div>
      <p class="text-xl text-gray-900 font-medium mb-2">Analyzing Receipt</p>
      <p class="text-gray-600">Our AI is extracting the details...</p>
    </div>
  </div>
</template>
