// engineer-assessment-frontend/src/components/SettingsButton.tsx
import { Check, Settings } from "lucide-react";
import { useState } from "react";
import { PROVIDERS } from "../types/constants";

interface SettingsButtonProps {
  selectedProvider: string;
  onProviderChange: (provider: string) => void;
}

export function SettingsButton({ selectedProvider, onProviderChange }: SettingsButtonProps) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="fixed top-6 right-6 z-40">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={`p-3 rounded-full shadow-lg border transition-all outline-none group relative ${
          isOpen ? "bg-blue-600 border-blue-600 text-white" : "bg-white/80 backdrop-blur-md border-slate-200 text-slate-600 hover:text-blue-600 hover:scale-105"
        }`}
      >
        <Settings className="w-5 h-5" />

        {/* Tooltip */}
        {!isOpen && <span className="absolute right-full mr-2 top-1/2 -translate-y-1/2 px-2 py-1 bg-slate-800 text-white text-xs rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">AI Settings</span>}
      </button>

      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />

          <div className="absolute right-0 mt-3 w-64 bg-white rounded-2xl shadow-xl border border-slate-100 p-2 z-50 animate-in fade-in zoom-in-95 duration-200 origin-top-right">
            <div className="px-3 py-2 text-xs font-bold text-slate-400 uppercase tracking-wider">Choose Your AI</div>
            <div className="space-y-1">
              {PROVIDERS.map((p) => (
                <button
                  key={p.id}
                  onClick={() => {
                    onProviderChange(p.id);
                    setIsOpen(false);
                  }}
                  className={`w-full flex items-center justify-between px-3 py-2.5 rounded-xl text-sm font-medium transition-all ${selectedProvider === p.id ? "bg-blue-50 text-blue-600" : "text-slate-600 hover:bg-slate-50 hover:text-slate-900"}`}
                >
                  {p.name}
                  {selectedProvider === p.id && <Check className="w-4 h-4 text-blue-600" />}
                </button>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

// frontend-vue/src/components/SettingsButton.vue
<script setup lang="ts">
import { useReceiptStore } from '@/stores/receipt';
import { Cpu, Settings, Sparkles, X } from 'lucide-vue-next';
import { storeToRefs } from 'pinia';
import { ref } from 'vue';

const store = useReceiptStore();
const { selectedProvider } = storeToRefs(store);

const isOpen = ref(false);

const providers = [
  { value: 'openai', label: 'OpenAI', icon: Cpu },
  { value: 'gemini', label: 'Gemini', icon: Sparkles },
];
</script>

<template>
  <div class="fixed top-4 right-4 z-50">
    <button
      class="p-3 rounded-full bg-white text-gray-600 hover:text-gray-900 hover:bg-gray-100 transition-all border border-gray-200 shadow-lg"
      @click="isOpen = !isOpen">
      <Settings class="w-5 h-5" />
    </button>

    <div v-if="isOpen" class="absolute right-0 mt-3 w-64 card overflow-hidden">
      <div class="flex items-center justify-between p-4 border-b border-gray-200">
        <span class="text-gray-900 font-medium">Settings</span>
        <button class="p-1 rounded-lg hover:bg-gray-100 text-gray-600 hover:text-gray-900 transition-colors"
          @click="isOpen = false">
          <X class="w-4 h-4" />
        </button>
      </div>

      <div class="p-4">
        <label class="text-sm text-gray-600 block mb-3">AI Provider</label>
        <div class="space-y-2">
          <button v-for="provider in providers" :key="provider.value"
            class="w-full flex items-center gap-3 p-3 rounded-xl transition-all" :class="selectedProvider === provider.value
              ? 'bg-blue-100 border border-blue-300 text-gray-900'
              : 'bg-gray-100 border border-transparent text-gray-600 hover:bg-gray-200'"
            @click="selectedProvider = provider.value">
            <component :is="provider.icon" class="w-5 h-5" />
            <span>{{ provider.label }}</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
